In [40]:
import pandas as pd
import uuid
import sys
import os
import django
import collections
#create django setup; needed otherwise we cannot use django models outside of django apps
sys.path.append("..")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "valueinvesting.settings")
django.setup()
from quickfs.models import KeyRatiosQuarter, IncomeStatementAnnual, TradedCompanies, IncomeStatementQuarter, BalanceSheetQuarter
from datetime import date, datetime
from pyxirr import xirr
from forex_python.converter import CurrencyRates

In [ ]:
quart1 = pd.read_csv("Data/")

In [44]:
c = CurrencyRates()
currency_date = '1999-01-03'

c.get_rate('USD', 'CHF', datetime.strptime(currency_date, '%Y-%m-%d'))

RatesNotAvailableError: Currency Rates Source Not Ready

In [36]:
dates = [date(2020, 1, 1), date(2021, 1, 1), date(2022, 1, 1)]
amounts = [-1000, 750, 500]

# feed columnar data
xirr(dates, amounts)

0.1750092646154511

In [27]:
key_ratios_quart = KeyRatiosQuarter.objects.filter(ticker_id = 'ANNX', period_end_date = '2021-09-01').values_list('period_end_price', 'ticker_id__currency', 'ticker_id__industry')

In [29]:
trading_log = pd.DataFrame(columns=['ticker', 'date', 'uuid', 'qty', 'type', 'price', 'currency'])

In [30]:
trading_log

Empty DataFrame
Columns: [ticker, date, uuid, qty, type, price, currency]
Index: []

In [31]:
trading_log['new_row'] = pd.Series(index=trading_log.index)

/var/folders/0k/p7xpfjb15zq_sj5w2mwmzv8w0000gn/T/ipykernel_34902/312934747.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  trading_log['new_row'] = pd.Series(index=trading_log.index)

In [32]:
trading_log

Empty DataFrame
Columns: [ticker, date, uuid, qty, type, price, currency, new_row]
Index: []

In [28]:
for ratio in key_ratios_quart:
    print(ratio)

SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.