In [1]:
from finvizfinance.screener.overview import Overview

In [2]:
foverview = Overview()

In [10]:
foverview.get_filters()

['Exchange',
 'Index',
 'Sector',
 'Industry',
 'Country',
 'Market Cap.',
 'P/E',
 'Forward P/E',
 'PEG',
 'P/S',
 'P/B',
 'Price/Cash',
 'Price/Free Cash Flow',
 'EPS growththis year',
 'EPS growthnext year',
 'EPS growthpast 5 years',
 'EPS growthnext 5 years',
 'Sales growthpast 5 years',
 'EPS growthqtr over qtr',
 'Sales growthqtr over qtr',
 'Dividend Yield',
 'Return on Assets',
 'Return on Equity',
 'Return on Investment',
 'Current Ratio',
 'Quick Ratio',
 'LT Debt/Equity',
 'Debt/Equity',
 'Gross Margin',
 'Operating Margin',
 'Net Profit Margin',
 'Payout Ratio',
 'InsiderOwnership',
 'InsiderTransactions',
 'InstitutionalOwnership',
 'InstitutionalTransactions',
 'Float Short',
 'Analyst Recom.',
 'Option/Short',
 'Earnings Date',
 'Performance',
 'Performance 2',
 'Volatility',
 'RSI (14)',
 'Gap',
 '20-Day Simple Moving Average',
 '50-Day Simple Moving Average',
 '200-Day Simple Moving Average',
 'Change',
 'Change from Open',
 '20-Day High/Low',
 '50-Day High/Low',
 '52-Week High/Low',
 'Pattern',
 'Candlestick',
 'Beta',
 'Average True Range',
 'Average Volume',
 'Relative Volume',
 'Current Volume',
 'Price',
 'Target Price',
 'IPO Date',
 'Shares Outstanding',
 'Float']

In [19]:
filter_dict ={'P/E': 'Under 10', 'EPS growthpast 5 years' : 'Over 10%', 'Return on Investment': 'Over +10%',  'Market Cap.' : 'Small ($300mln to $2bln)' }

In [20]:
foverview.set_filter(filters_dict=filter_dict)

In [21]:
df = foverview.screener_view()

In [23]:
df.sort_values(by=['P/E'])

,Ticker\n\n,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume
153,ZIM,ZIM Integrated Shipping Services Ltd.,Industrials,Marine Shipping,Israel,1720000000.0,0.64,15.15,0.0007,2034764.0
105,OBE,Obsidian Energy Ltd.,Energy,Oil & Gas E&P,Canada,713570000.0,0.72,6.94,-0.028,327593.0
122,RTC,Baijiayun Group Ltd,Technology,Software - Application,China,474660000.0,0.73,6.9,0.0004,6537.0
103,NMM,Navios Maritime Partners L.P.,Industrials,Marine Shipping,Monaco,698150000.0,1.23,23.65,-0.0105,88870.0
1,AMBC,"Ambac Financial Group, Inc.",Financial,Insurance - Specialty,USA,655290000.0,1.32,14.05,-0.0064,178804.0
...,...,...,...,...,...,...,...,...,...,...
27,CSTR,"CapStar Financial Holdings, Inc.",Financial,Banks - Regional,USA,310350000.0,9.74,14.66,-0.0148,35916.0
49,FCF,First Commonwealth Financial Corporation,Financial,Banks - Regional,USA,1470000000.0,9.79,14.34,-0.0069,526261.0
93,MCBS,"MetroCity Bankshares, Inc.",Financial,Banks - Regional,USA,559220000.0,9.89,21.65,0.0098,11457.0
6,BANC,"Banc of California, Inc.",Financial,Banks - Regional,USA,792270000.0,9.94,14.02,-0.0134,1718249.0
37,DNOW,NOW Inc.,Energy,Oil & Gas Equipment & Services,USA,1230000000.0,9.99,11.61,0.0193,458435.0

In [22]:
df.head()

,Ticker\n\n,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume
0,AMAL,Amalgamated Financial Corp.,Financial,Banks - Regional,USA,569990000.0,6.66,19.5,-0.023,96210.0
1,AMBC,"Ambac Financial Group, Inc.",Financial,Insurance - Specialty,USA,655290000.0,1.32,14.05,-0.0064,178804.0
2,AMRK,"A-Mark Precious Metals, Inc.",Financial,Capital Markets,USA,926950000.0,6.59,40.62,-0.0042,101158.0
3,AROW,Arrow Financial Corporation,Financial,Banks - Regional,USA,336020000.0,7.52,20.34,0.0109,30983.0
4,ASC,Ardmore Shipping Corporation,Industrials,Marine Shipping,Bermuda,552480000.0,2.98,13.75,-0.0234,1244600.0

In [16]:
foverview.get_filter_options('Market Cap.')

['Any',
 'Mega ($200bln and more)',
 'Large ($10bln to $200bln)',
 'Mid ($2bln to $10bln)',
 'Small ($300mln to $2bln)',
 'Micro ($50mln to $300mln)',
 'Nano (under $50mln)',
 '+Large (over $10bln)',
 '+Mid (over $2bln)',
 '+Small (over $300mln)',
 '+Micro (over $50mln)',
 '-Large (under $200bln)',
 '-Mid (under $10bln)',
 '-Small (under $2bln)',
 '-Micro (under $300mln)']

In [5]:
filters_dict = {'Exchange':'AMEX','Sector':'Basic Materials'}
foverview.set_filter(filters_dict=filters_dict)
df = foverview.screener_view()
df.head()

,Ticker\n\n,Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume
0,AAU,Almaden Minerals Ltd.,Basic Materials,Gold,Canada,19580000.0,NaN,0.15,-0.0434,164245.0
1,ASM,Avino Silver & Gold Mines Ltd.,Basic Materials,Other Precious Metals & Mining,Canada,86740000.0,42.41,0.72,-0.0378,416539.0
2,AUMN,Golden Minerals Company,Basic Materials,Other Precious Metals & Mining,USA,9750000.0,NaN,1.28,-0.0376,86237.0
3,AUST,Austin Gold Corp.,Basic Materials,Gold,Canada,11500000.0,NaN,0.88,0.0042,8127.0
4,BTG,B2Gold Corp.,Basic Materials,Gold,Canada,4390000000.0,14.13,3.39,-0.0287,5250005.0

In [1]:
endRevenue = 94836000000 + 117154000000 + 90146000000 + 82959000000
startRevenue = 97278000000 + 123945000000 + 83360000000 + 81434000000

In [2]:
endRevenue

385095000000

In [3]:
startRevenue

386017000000

In [4]:
cagrTTM = endRevenue/startRevenue -1

In [6]:
cagrTTM*100

-0.2388495843447358

In [ ]:
2023-04-01
2022-06-25


2023-06-30
2022-09-30