In [10]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [5]:
data_q1 = pd.read_csv("Data/USA/bulk_quarterly_financials_1.csv")
data_q2 = pd.read_csv("Data/USA/bulk_quarterly_financials_2.csv")
data_q3 = pd.read_csv("Data/USA/bulk_quarterly_financials_3.csv")
data_q4 = pd.read_csv("Data/USA/bulk_quarterly_financials_4.csv")
data_q5 = pd.read_csv("Data/USA/bulk_quarterly_financials_5.csv")

In [6]:
data_q1.head()

,symbol,qfs_symbol,exchange,name,company_type,currency,industry,period_type,period_end_date,revenue,...,assets_to_equity_median,debt_to_assets_median,debt_to_equity_median,roi_median,equity_to_assets_median,underwriting_margin_median,nim_median,earning_assets_to_equity_median,loans_to_deposits_median,loan_loss_reserve_to_loans_median
0,ANNX,ANNX:US,NASDAQ,Annexon Inc,normal,USD,Biotechnology,FQ,2021-09,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ANNX,ANNX:US,NASDAQ,Annexon Inc,normal,USD,Biotechnology,FQ,2020-03,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ANNX,ANNX:US,NASDAQ,Annexon Inc,normal,USD,Biotechnology,FQ,2019-12,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ANNX,ANNX:US,NASDAQ,Annexon Inc,normal,USD,Biotechnology,FQ,2019-06,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ANNX,ANNX:US,NASDAQ,Annexon Inc,normal,USD,Biotechnology,FQ,2019-03,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
data_q1[(data_q1['symbol'] == 'TIMGF') & (data_q1['period_end_date'] == '2019-01')]['period_end_price']

14766    0.06
Name: period_end_price, dtype: float64

In [16]:
data_q1[(data_q1['symbol'] == 'DCGD') & (data_q1['period_end_date'] == '2019-02')]

Empty DataFrame
Columns: [symbol, qfs_symbol, exchange, name, company_type, currency, industry, period_type, period_end_date, revenue, cogs, gross_profit, sga, rnd, special_charges, other_opex, total_opex, operating_income, interest_income, interest_expense, net_interest_income_normal, other_nonoperating_income, pretax_income, income_tax, net_income_continuing, net_income_discontinued, income_allocated_to_minority_interest, other_income_statement_items, net_income, preferred_dividends, net_income_available_to_shareholders, eps_basic, eps_diluted, shares_basic, shares_diluted, shares_eop, shares_eop_change, premiums_earned, net_investment_income, fees_and_other_income, net_policyholder_claims_expense, policy_acquisition_expense, interest_expense_insurance, total_interest_income, total_interest_expense, net_interest_income, total_noninterest_revenue, credit_losses_provision, net_interest_income_after_credit_losses_provision, total_noninterest_expense, da_income_statement_supplemental, cash_and_equiv, st_investments, receivables, inventories, other_current_assets, total_current_assets, equity_and_other_investments, ppe_gross, accumulated_depreciation, ppe_net, intangible_assets, goodwill, other_lt_assets, total_assets, accounts_payable, tax_payable, current_accrued_liabilities, st_debt, current_deferred_revenue, current_deferred_tax_liability, current_capital_leases, other_current_liabilities, total_current_liabilities, lt_debt, noncurrent_capital_leases, pension_liabilities, noncurrent_deferred_revenue, other_lt_liabilities, total_liabilities, common_stock, preferred_stock, retained_earnings, aoci, apic, treasury_stock, other_equity, minority_interest_liability, total_equity, total_liabilities_and_equity, total_investments, deferred_policy_acquisition_cost, unearned_premiums, future_policy_benefits, loans_gross, allowance_for_loan_losses, unearned_income, loans_net, deposits_liability, cfo_net_income, ...]
Index: []

In [3]:
annual_data = pd.read_csv('bulk_annual_financials_sample_small.csv')

In [ ]:
def opex_csy_check(row):
    """
    Function which checks that the operating expenses data is consistent. We have different use cases for "normal" companies (everything except banks & insurances), banks & insurances
    
    normal use case:
        total opex = cogs + sga + rnd + special_charges + other_opex
    """
    if row['company_type'] == 'normal':
        print('we check a normal company')

In [4]:
annual_data.head()

,symbol,qfs_symbol,exchange,name,company_type,currency,industry,period_type,period_end_date,revenue,...,assets_to_equity_median,debt_to_assets_median,debt_to_equity_median,roi_median,equity_to_assets_median,underwriting_margin_median,nim_median,earning_assets_to_equity_median,loans_to_deposits_median,loan_loss_reserve_to_loans_median
0,AAPL,AAPL:US,NASDAQ,Apple Inc,normal,USD,"Technology Hardware, Storage & Peripherals",FY,2011-09,1.082490e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAPL,AAPL:US,NASDAQ,Apple Inc,normal,USD,"Technology Hardware, Storage & Peripherals",FY,2014-09,1.827950e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AAPL,AAPL:US,NASDAQ,Apple Inc,normal,USD,"Technology Hardware, Storage & Peripherals",FY,2013-09,1.709100e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAPL,AAPL:US,NASDAQ,Apple Inc,normal,USD,"Technology Hardware, Storage & Peripherals",FY,2002-09,5.742000e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAPL,AAPL:US,NASDAQ,Apple Inc,normal,USD,"Technology Hardware, Storage & Peripherals",FY,2010-09,6.522500e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN