In [1]:
import pandas as pd
import psycopg2, os

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
#define database connection
psycopg2_connection = psycopg2.connect(host="localhost", database="value-investing-dev", user="postgres", password="v,1846PSVv,1846PSV")

In [3]:
data_europe = pd.read_csv("Data/europe/bulk_quarterly_financials_europe.csv")

In [4]:
rename_columns = {'symbol' : 'ticker_id'}

In [5]:
data_europe.rename(columns=rename_columns, inplace=True)

In [6]:
data_europe[data_europe['ticker_id'] == 'DIE']

      ticker_id qfs_symbol           exchange                name  \
8100        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8101        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8102        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8103        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8104        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8105        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8106        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8107        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8108        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8109        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8110        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8111        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8112        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8113        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8114        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8115        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8116        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8117        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8118        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8119        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8120        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8121        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8122        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8123        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8124        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8125        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8126        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8127        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8128        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8129        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8130        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8131        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8132        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8133        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8134        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8135        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8136        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8137        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8138        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8139        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8140        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8141        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8142        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8143        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8144        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8145        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8146        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8147        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8148        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8149        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8150        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8151        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8152        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8153        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8154        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8155        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8156        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8157        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8158        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8159        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8160        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8161        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8162        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
8163        DIE     DIE:BE  Euronext Brussels  D'Ieteren Group SA
26245       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26246       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26247       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26248       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26249       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26250       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26251       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26252       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26253       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26254       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26255       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26256       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26257       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26258       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26259       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26260       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26261       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26262       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26263       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26264       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26265       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26266       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26267       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26268       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26269       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26270       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26271       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26272       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26273       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26274       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26275       DIE     DIE:DE          Stuttgart   Dierig Holding AG
26276       DIE     DIE:DE          Stuttgart   Dierig Holding AG

      company_type currency                          industry period_type  \
8100        normal      EUR                  Specialty Retail          FQ
8101        normal      EUR                  Specialty Retail          FQ
8102        normal      EUR                  Specialty Retail          FQ
8103        normal      EUR                  Specialty Retail          FQ
8104        normal      EUR                  Specialty Retail          FQ
8105        normal      EUR                  Specialty Retail          FQ
8106        normal      EUR                  Specialty Retail          FQ
8107        normal      EUR                  Specialty Retail          FQ
8108        normal      EUR                  Specialty Retail          FQ
8109        normal      EUR                  Specialty Retail          FQ
8110        normal      EUR                  Specialty Retail          FQ
8111        normal      EUR                  Specialty Retail          FQ
8112        normal      EUR                  Specialty Retail          FQ
8113        normal      EUR                  Specialty Retail          FQ
8114        normal      EUR                  Specialty Retail          FQ
8115        normal      EUR                  Specialty Retail          FQ
8116        normal      EUR                  Specialty Retail          FQ
8117        normal      EUR                  Specialty Retail          FQ
8118        normal      EUR                  Specialty Retail          FQ
8119        normal      EUR                  Specialty Retail          FQ
8120        normal      EUR                  Specialty Retail          FQ
8121        normal      EUR                  Specialty Retail          FQ
8122        normal      EUR                  Specialty Retail          FQ
8123        normal      EUR                  Specialty Retail          FQ
8124        normal      EUR                  Specialty Retail          FQ
8125        normal      EUR                  Specialty Retail          FQ
8126        normal      EUR                  Specialty Retail          FQ
8127        normal      EUR                  Specialty Retail          FQ
8128        normal      EUR                  Specialty Retail          FQ
8129        normal      EUR                  Specialty Retail          FQ
8130        normal      EUR                  Specialty Retail          FQ
8131        normal      EUR                  Specialty Retail          FQ
8132        normal      EUR                  Specialty Retail          FQ
8133        normal      EUR                  Specialty Retail          FQ
8134        normal      EUR                  Specialty Retail          FQ
8135        normal      EUR                  Specialty Retail          FQ
8136        normal      EUR                  Specialty Retail          FQ
8137        normal      EUR                  Specialty Retail          FQ
8138        normal      EUR                  Specialty Retail          FQ
8139        normal      EUR                  Specialty Retail          FQ
8140        normal      EUR                  Specialty Retail          FQ
8141        normal      EUR                  Specialty Retail          FQ
8142        normal      EUR                  Specialty Retail          FQ
8143        normal      EUR                  Specialty Retail          FQ
8144        normal      EUR                  Specialty Retail          FQ
8145        normal      EUR                  Specialty Retail          FQ
8146        normal      EUR                  Specialty Retail          FQ
8147        normal      EUR                  Specialty Retail          FQ
8148        normal      EUR                  Specialty Retail          FQ
8149        normal      EUR                  Specialty Retail          FQ
8150        normal      EUR                  Specialty Retail          FQ
8151        normal      EUR                  Specialty Retail          FQ
8152        normal      EUR                  Specialty Retail          FQ
8153        normal      EUR                  Specialty Retail          FQ
8154        normal      EUR                  Specialty Retail          FQ
8155        normal      EUR                  Specialty Retail          FQ
8156        normal      EUR                  Specialty Retail          FQ
8157        normal      EUR                  Specialty Retail          FQ
8158        normal      EUR                  Specialty Retail          FQ
8159        normal      EUR                  Specialty Retail          FQ
8160        normal      EUR                  Specialty Retail          FQ
8161        normal      EUR                  Specialty Retail          FQ
8162        normal      EUR                  Specialty Retail          FQ
8163        normal      EUR                  Specialty Retail          FQ
26245       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26246       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26247       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26248       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26249       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26250       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26251       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26252       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26253       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26254       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26255       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26256       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26257       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26258       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26259       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26260       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26261       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26262       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26263       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26264       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26265       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26266       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26267       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26268       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26269       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26270       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26271       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26272       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26273       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26274       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26275       normal      EUR  Textiles, Apparel & Luxury Goods          FQ
26276       normal      EUR  Textiles, Apparel & Luxury Goods          FQ

      period_end_date       revenue          cogs  gross_profit          sga  \
8100          2008-09  0.000000e+00  0.000000e+00           0.0          0.0
8101          2008-12  0.000000e+00  0.000000e+00           0.0          0.0
8102          2009-03  1.610750e+09  1.103200e+09   507550000.0  416350000.0
8103          2009-06  1.610750e+09  1.103200e+09   507550000.0  416350000.0
8104          2009-09  1.524100e+09  1.017100e+09   507000000.0  404850000.0
8105          2009-12  1.524100e+09  1.017100e+09   507000000.0  404850000.0
8106          2010-03  1.505550e+09  1.038700e+09   466850000.0  363950000.0
8107          2010-06  1.505550e+09  1.038700e+09   466850000.0  363950000.0
8108          2010-09  1.261350e+09  8.778000e+08   383550000.0  317850000.0
8109          2010-12  1.261350e+09  8.778000e+08   383550000.0  317850000.0
8110          2011-03  1.587700e+09  1.125150e+09   462550000.0  364750000.0
8111          2011-06  1.587700e+09  1.125150e+09   462550000.0  364750000.0
8112          2011-09  1.400950e+09  9.980000e+08   402950000.0  319900000.0
8113          2011-12  1.400950e+09  9.980000e+08   402950000.0  319900000.0
8114          2012-03  1.506650e+09  1.079300e+09   427350000.0  353600000.0
8115          2012-06  1.506650e+09  1.079300e+09   427350000.0  353600000.0
8116          2012-09  1.250600e+09  8.513000e+08   399300000.0  334650000.0
8117          2012-12  1.250600e+09  8.513000e+08   399300000.0  334650000.0
8118          2013-03  1.489000e+09  1.045700e+09   443300000.0  377950000.0
8119          2013-06  1.489000e+09  1.045700e+09   443300000.0  377950000.0
8120          2013-09  1.246250e+09  8.319500e+08   414300000.0  374050000.0
8121          2013-12  1.246250e+09  8.319500e+08   414300000.0  374050000.0
8122          2014-03  1.486850e+09  1.054350e+09   432500000.0  379200000.0
8123          2014-06  1.486850e+09  1.054350e+09   432500000.0  379200000.0
8124          2014-09  1.239700e+09  8.134500e+08   426250000.0  379250000.0
8125          2014-12  1.239700e+09  8.134500e+08   426250000.0  379250000.0
8126          2015-03  1.599550e+09  1.111950e+09   487600000.0  410450000.0
8127          2015-06  1.599550e+09  1.111950e+09   487600000.0  410450000.0
8128          2015-09  1.418150e+09  9.728000e+08   445350000.0  401000000.0
8129          2015-12  1.418150e+09  9.728000e+08   445350000.0  401000000.0
8130          2016-03  1.709500e+09  1.190450e+09   519050000.0  436400000.0
8131          2016-06  1.709500e+09  1.190450e+09   519050000.0  436400000.0
8132          2016-09 -1.263500e+08  2.078000e+08  -334150000.0 -291450000.0
8133          2016-12 -1.263500e+08  2.078000e+08  -334150000.0 -291450000.0
8134          2017-03  9.463500e+08  8.263500e+08   120000000.0   87100000.0
8135          2017-06  9.463500e+08  8.263500e+08   120000000.0   87100000.0
8136          2017-09  7.812000e+08  6.662500e+08   114950000.0  100050000.0
8137          2017-12  7.812000e+08  6.662500e+08   114950000.0  100050000.0
8138          2018-03  1.036700e+09  9.018500e+08   134850000.0   98600000.0
8139          2018-06  1.036700e+09  9.018500e+08   134850000.0   98600000.0
8140          2018-09  7.538000e+08  6.451500e+08   108650000.0   89400000.0
8141          2018-12  7.538000e+08  6.451500e+08   108650000.0   89400000.0
8142          2019-03  1.005300e+09  8.734500e+08   131850000.0   95300000.0
8143          2019-06  1.005300e+09  8.734500e+08   131850000.0   95300000.0
8144          2019-09  8.941000e+08  7.782000e+08   115900000.0   95800000.0
8145          2019-12  8.941000e+08  7.782000e+08   115900000.0   95800000.0
8146          2020-03  7.554000e+08  6.596000e+08    95800000.0  100050000.0
8147          2020-06  7.554000e+08  6.596000e+08    95800000.0  100050000.0
8148          2020-09  9.036000e+08  7.791000e+08   124500000.0   87150000.0
8149          2020-12  9.036000e+08  7.791000e+08   124500000.0   87150000.0
8150          2021-03  9.455500e+08  8.171500e+08   128400000.0   96550000.0
8151          2021-06  9.455500e+08  8.171500e+08   128400000.0   96550000.0
8152          2021-09  7.347000e+08  6.235000e+08   111200000.0   91850000.0
8153          2021-12  7.347000e+08  6.235000e+08   111200000.0   91850000.0
8154          2022-03  9.549500e+08  8.067000e+08   148250000.0  108100000.0
8155          2022-06  9.549500e+08  8.067000e+08   148250000.0  108100000.0
8156          2022-09  1.402350e+09  1.065300e+09   337050000.0  282350000.0
8157          2022-12  1.402350e+09  1.065300e+09   337050000.0  282350000.0
8158          2023-03  2.042700e+09  1.578600e+09   464100000.0  357750000.0
8159          2023-06  2.042700e+09  1.578600e+09   464100000.0  357750000.0
8160          2023-09  1.949100e+09  1.510150e+09   438950000.0  371250000.0
8161          2023-12  1.949100e+09  1.510150e+09   438950000.0  371250000.0
8162          2024-03  2.151500e+09  1.651400e+09   500100000.0  398350000.0
8163          2024-06  2.151500e+09  1.651400e+09   500100000.0  398350000.0
26245         2007-12  0.000000e+00  0.000000e+00           0.0          0.0
26246         2009-06  2.921700e+07  1.977800e+07     9439000.0          0.0
26247         2009-12  0.000000e+00  0.000000e+00           0.0          0.0
26248         2010-06  3.419400e+07  2.422200e+07     9972000.0          0.0
26249         2010-12  3.693000e+07  2.443100e+07    12499000.0          0.0
26250         2011-06  3.729500e+07  2.608800e+07    11207000.0          0.0
26251         2011-12  3.965700e+07  2.463800e+07    15019000.0          0.0
26252         2012-06  3.591500e+07  2.466900e+07    11246000.0          0.0
26253         2012-12  3.689400e+07  2.446100e+07    12433000.0          0.0
26254         2013-06  3.472000e+07  2.279400e+07    11926000.0          0.0
26255         2013-12  3.753400e+07  2.461900e+07    12915000.0          0.0
26256         2014-06  3.576000e+07  2.320700e+07    12553000.0          0.0
26257         2014-12  3.729600e+07  2.341800e+07    13878000.0          0.0
26258         2015-06  3.665000e+07  2.403800e+07    12612000.0          0.0
26259         2015-12  3.926800e+07  2.507500e+07    14193000.0          0.0
26260         2016-06  3.424200e+07  2.147500e+07    12767000.0          0.0
26261         2016-12  3.412200e+07  2.132900e+07    12793000.0          0.0
26262         2017-06  3.321300e+07  2.053400e+07    12679000.0          0.0

In [62]:
income_statement_fields = ["symbol", "period_end_date", "revenue", "cogs", "gross_profit", "sga", "rnd", "special_charges", "other_opex", "total_opex", "operating_income", "interest_income", "interest_expense", "net_interest_income_normal", "other_nonoperating_income", "pretax_income", "income_tax", "net_income_continuing", "net_income_discontinued", "income_allocated_to_minority_interest", "other_income_statement_items", "net_income", "preferred_dividends", "net_income_available_to_shareholders", "eps_basic", "eps_diluted", "shares_basic", "shares_diluted", "shares_eop", "shares_eop_change", "premiums_earned", "net_investment_income", "fees_and_other_income", "net_policyholder_claims_expense", "policy_acquisition_expense", "interest_expense_insurance", "total_interest_income", "total_interest_expense", "net_interest_income", "total_noninterest_revenue", "credit_losses_provision", "net_interest_income_after_credit_losses_provision", "total_noninterest_expense", "da_income_statement_supplemental" ]
relevant_fields = income_statement_fields
rename_columns = {'symbol' : 'ticker_id'}

In [63]:
   #extract relevant fields
df_extracted = data_europe[relevant_fields]

#rename columns
df_extracted.rename(columns=rename_columns, inplace=True)

/var/folders/0k/p7xpfjb15zq_sj5w2mwmzv8w0000gn/T/ipykernel_66320/3730017275.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_extracted.rename(columns=rename_columns, inplace=True)

In [64]:
    #remove ttm row (not possible to store string in date column)
df_extracted = df_extracted[df_extracted.period_end_date != 'TTM']

In [65]:
def transform_date_to_string(date):
    return date.strftime('%Y-%m-%d')

def transform_date(date):
    return date + "-01"

In [66]:
df_extracted['period_end_date'] = df_extracted['period_end_date'].apply(transform_date)

In [67]:
df_extracted[df_extracted['ticker_id'] == 'DIE']

,ticker_id,period_end_date,revenue,cogs,gross_profit,sga,rnd,special_charges,other_opex,total_opex,operating_income,interest_income,interest_expense,net_interest_income_normal,other_nonoperating_income,pretax_income,income_tax,net_income_continuing,net_income_discontinued,income_allocated_to_minority_interest,other_income_statement_items,net_income,preferred_dividends,net_income_available_to_shareholders,eps_basic,eps_diluted,shares_basic,shares_diluted,shares_eop,shares_eop_change,premiums_earned,net_investment_income,fees_and_other_income,net_policyholder_claims_expense,policy_acquisition_expense,interest_expense_insurance,total_interest_income,total_interest_expense,net_interest_income,total_noninterest_revenue,credit_losses_provision,net_interest_income_after_credit_losses_provision,total_noninterest_expense,da_income_statement_supplemental
8100,DIE,2008-09-01,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0000,0.0000,54393000.0,54470000.0,55303000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8101,DIE,2008-12-01,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0000,0.0000,54393000.0,54470000.0,55303000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
8102,DIE,2009-03-01,1.610750e+09,1.103200e+09,507550000.0,416350000.0,0.0,0.0,11600000.0,427950000.0,79600000.0,0.0,-32100000.0,-32100000.0,0.0,47500000.0,-4750000.0,42750000.0,0.0,3050000.0,-2.750000e+06,43050000.0,0.0,43050000.0,0.7275,0.7275,54340000.0,54341000.0,55303000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73000000.0
8103,DIE,2009-06-01,1.610750e+09,1.103200e+09,507550000.0,416350000.0,0.0,0.0,11600000.0,427950000.0,79600000.0,0.0,-32100000.0,-32100000.0,0.0,47500000.0,-4750000.0,42750000.0,0.0,3050000.0,-2.750000e+06,43050000.0,0.0,43050000.0,0.7275,0.7275,54340000.0,54341000.0,55303000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73000000.0
8104,DIE,2009-09-01,1.524100e+09,1.017100e+09,507000000.0,404850000.0,0.0,0.0,16850000.0,421700000.0,85300000.0,0.0,-25200000.0,-25200000.0,0.0,60100000.0,-11750000.0,48350000.0,0.0,9200000.0,-9.100000e+06,48450000.0,0.0,48450000.0,0.7175,0.7125,54237000.0,54417000.0,55303000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81700000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26272,DIE,2022-06-01,2.547800e+07,1.218200e+07,13296000.0,0.0,0.0,0.0,10473000.0,10473000.0,2823000.0,0.0,-376000.0,-376000.0,0.0,2447000.0,-485000.0,1962000.0,0.0,-4000.0,-2.220446e-10,1958000.0,0.0,1958000.0,0.4800,0.4800,4103000.0,4103000.0,4103000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1340000.0
26273,DIE,2022-12-01,2.664400e+07,1.384200e+07,12802000.0,0.0,0.0,0.0,10290000.0,10290000.0,2512000.0,0.0,-367000.0,-367000.0,0.0,2145000.0,-1052000.0,1093000.0,0.0,-5000.0,1.000000e+03,1089000.0,0.0,1089000.0,0.2600,0.2600,4103000.0,4103000.0,4103000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1338000.0
26274,DIE,2023-06-01,2.556800e+07,1.217100e+07,13397000.0,0.0,0.0,0.0,10857000.0,10857000.0,2540000.0,0.0,-599000.0,-599000.0,0.0,1941000.0,-393000.0,1548000.0,0.0,-4000.0,0.000000e+00,1544000.0,0.0,1544000.0,0.3760,0.3760,4103000.0,4103000.0,4103000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1355000.0
26275,DIE,2023-12-01,2.442100e+07,1.110600e+07,13315000.0,0.0,0.0,0.0,10914000.0,10914000.0,2401000.0,0.0,-687000.0,-687000.0,0.0,1714000.0,-819000.0,895000.0,0.0,-5000.0,0.000000e+00,890000.0,0.0,890000.0,0.2240,0.2170,4103000.0,4103000.0,4103000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1380000.0
26276,DIE,2024-06-01,2.527500e+07,1.126500e+07,14010000.0,0.0,0.0,0.0,10613000.0,10613000.0,3397000.0,0.0,-626000.0,-626000.0,0.0,2771000.0,-758000.0,2013000.0,0.0,-4000.0,0.000000e+00,2009000.0,0.0,2009000.0,0.4900,0.4900,4103000.0,4103000.0,4103000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1373000.0